name: Deploy AWS Lambda
# This workflow is triggered on pushes to the repository.
on:
  push:
    # This workflow will run on pushes to the master branch
    branches:
      - master
    # Only run this workflow for changes to the lambda directory
    paths:
      - 'lambda/**'

# Jobs are groups of steps that run in parallel.
jobs:
  # This workflow contains jobs called deploy-lambda
  deploy-lambda: 
    # specify runner
    runs-on: ubuntu-latest
    # Steps are a sequence of tasks that will be run in job
    steps:
      # Use resuable action to checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup python
        # Use resuable action to setup python version 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        # Upgrade pip and install dependencies from lambda directory and output to lambda directory
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/
      
      - name: Configure AWS credentials
        # Use reusable action to configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy Lambda
        # Zip the lambda directory and update the lambda function code
        run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code --function-name my-function --zip-file fileb://lambda.zip